### ISSUE TITLE
Validação de Cadastro

### ISSUE THREAD

**Issue by Rayaninha** [Rayaninha/AgroVen#1]
- [ ] Validação de Cadastro por e-mail

**Comment by Joanna-Victoria** [comment]
[a base do código foi feita por esse vídeo](https://www.youtube.com/watch?v=THQujIyE7Tg)

**código ainda não atualizado para o projeto, é apenas uma base**
[cadastro.txt](https://github.com/Rayaninha/AgroVen/files/7550807/cadastro.txt)
