### ISSUE TITLE
Tela Home

### ISSUE THREAD

**Issue by Rayaninha** [Rayaninha/AgroVen#19]
Eu como **desenvolvedora** desejo **codar a tela inicial não logada** para **direcionar as demais telas**.

- [ ] Subir em pdf ou png o protótipo do Figma;
- [ ] Commitar a Tela Home;

**Comment by Rayaninha** [comment]
**Problema nas imagens do Svelte**
- [Projeto sem o Svelte](https://drive.google.com/drive/folders/1V-iK_6pw-y7K0KmpLUqyc5qEOkKT2IdL?usp=sharing) para visualização do design.

**Comment by Luanjoss** [comment]
https://www.figma.com/file/A0UMljC6wv8jcF685wjSit/Agroven?node-id=0%3A1

**Comment by Luanjoss** [comment]
Houve uma atualização na interface da tela do cliente adicionando novos elementos e o ''passo a passo'' para orientar o usuário do site
