### ISSUE TITLE
Autenticação

### ISSUE THREAD

**Issue by Rayaninha** [Rayaninha/AgroVen#20]
Estudar as formas de autenticação propostas:

- [ ] Por cadastro do site;
- [ ] Por e-mail google;

**Comment by Joanna-Victoria** [comment]
[autenticação gmail](https://mariovalney.com/como-colocar-o-login-do-google-no-meu-site/)

uma maneira de aplicar a autenticação por meio do e-mail google.

**Comment by Rayaninha** [comment]
[autenticação com o banco de dados e php](https://www.devmedia.com.br/criando-um-sistema-de-cadastro-e-login-com-php-e-mysql/37213)

**Comment by Joanna-Victoria** [comment]
[base da autenticação](https://www.youtube.com/watch?v=jze3TasX5DA)
