### ISSUE TITLE
Tela Login/ Registro

### ISSUE THREAD

**Issue by Rayaninha** [Rayaninha/AgroVen#23]
eu como dev desejo criar um pop-up de login/ registro para autenticação do usuário.

- [x] #24

**Comment by MizaelJR17** [comment]
[Agroven.zip](https://github.com/Rayaninha/AgroVen/files/7464990/Agroven.zip)

**Comment by Luanjoss** [comment]
https://www.figma.com/file/A0UMljC6wv8jcF685wjSit/Agroven?node-id=0%3A1

**Comment by Luanjoss** [comment]
Adicionado novas telas, Tela de mensagem, Sobre e Tela do Cliente. A tela de login sofreu mudanças no design de cores, para harmoniza o ambiente.
