### ISSUE TITLE
Elaborar Modelo Entidade Relacionamento do Banco de Dados

### ISSUE THREAD

**Issue by rayanesal** [Rayaninha/AgroVen#4]
Como **desenvolvedor** quero **construir um modelo ER** para melhor **visualização dos atributos, entidades e relacionamentos.**

- [x] Utilizar ferramenta para modelagem.
- [x] Identificar atributos.
- [x] Identificar entidades.
- [x] Identificar relacionamentos
- [x] Gerar arquivo de exportação (.png, .pdf, .jpg, ...)

**Comment by lilialnas** [comment]
Adicionando que: essa entidade da venda precisa guardar data/hora da venda e quais itens foram comprados (semelhante a um pedido e itens de pedido). Teremos uma entidade associativa em venda. 
Acredito que animal pode ser visto como um produto, sem precisar de uma tabela para animal.
Todo produto vai precisar de uma unidade de medida (peso, maço etc).
